let sharkDodo = " Shark, doo doo doo doo doo doo";
let baby = "baby";
let Lets = "let's go hunt, doo doo doo doo doo doo";
let Run = "Run away, doo doo doo doo doo doo";
let Safe = "Safe at last, doo doo doo doo doo doo";
let babycat = "Baby Cat, meow meow meow meow meow meow";
console.log(baby + sharkDodo);
console.log(baby + sharkDodo);
console.log(baby + sharkDodo);
console.log(baby + sharkDodo);
let Mommy = "Mommy";
console.log(Mommy + sharkDodo);
console.log(Mommy + sharkDodo);
console.log(Mommy + sharkDodo);
console.log(Mommy + sharkDodo);
let Daddy = "Daddy";
console.log(Daddy + sharkDodo);
console.log(Daddy + sharkDodo);
console.log(Daddy + sharkDodo);
console.log(Daddy + sharkDodo);
let Grandma = "Grandma";
console.log(Grandma + sharkDodo);
console.log(Grandma + sharkDodo);
console.log(Grandma + sharkDodo);
console.log(Grandma + sharkDodo);
console.log(Lets);
console.log(Lets);
console.log(Lets);
console.log(Lets);
console.log(Run);
console.log(Run);
console.log(Run);
console.log(Run);
console.log(Safe);
console.log(Safe);
console.log(Safe);
console.log(Safe);
console.log(babycat);
console.log(babycat);
console.log(babycat);
console.log(babycat);
